security:
    firewalls:
        # Firewall de la parte de administración o backend
        backend:
            pattern:        ^/easyadmin
            provider:       administradores
            http_basic:     ~
        
        # Firewall global utilizado en la parte pública o frontend
        frontend:
            pattern:        ^/*
            provider:       usuarios
            anonymous:      ~
            form_login:
                login_path: usuario_login
                check_path: usuario_login_check
                remember_me: true
#                default_target_path: /usuario/compras
            logout:
                path: usuario_logout
            switch_user : true

    access_control:
        - { path: ^/(es|en)/usuario/(login|registro), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en)/usuario/*, roles: ROLE_USUARIO }
        - { path: ^/easyadmin/*,  roles: ROLE_ADMIN }

    providers:
        # Usuarios del frontend
        usuarios:
            entity: { class: AppBundle\Entity\Usuario, property: email }
        administradores:
            memory:
                users:
                    # usuario = admin, contraseña = 1234
                    admin: { password: '$2y$13$w700yeSs8FxMLrEXaCATgehosZf9vx09RbwKddswl9LN/22dKL2qO', roles: ROLE_ADMIN }

            
            
    encoders:
        AppBundle\Entity\Usuario: bcrypt
        Symfony\Component\Security\Core\User\User: { algorithm: bcrypt, cost: 8 }

